### ISSUE TITLE
Not working for Collections

### ISSUE THREAD

**Issue by amandafrench** [anuragji/DefaultSort#1]
Great plugin! Works like a charm for Items, but for some reason the default sort for the Collections Browse isn't taking hold on my implementation. I've got the latest version of Omeka. 

I'm trying to get the Collections to sort alphabetically by title, ascending, but no matter what what setting I choose they still wind up sorting descending by Date Added. See http://steepletoplibrary.org/collections/browse and the attached screenshot. 

![screenshot 2014-09-03 10 27 26](https://cloud.githubusercontent.com/assets/227453/4135490/a880bdb6-3376-11e4-8e75-f409e6b01c05.png)

**Comment by rishijavia** [comment]
Hi there, thanks for the plugin! Definitely saved lot of time redirecting stuff around.
I am having a similar issue where the plugin is working perfectly for the /items/browse but its sorting by date added for /collections/browse. I am using the latest version of the code.

**Comment by anuragji** [comment]
@rishijavia - I have not gotten a chance to look into it yet, but it is on my list. Unfortunately I need to first fix another issue on my dev server before getting there. Sorry for the delay

**Comment by rishijavia** [comment]
@anuragji - thanks for looking into this, and we are still into development stage so time is not a huge issue as of now. Some more information about our omeka/system that might help you:
Omeka Version: 2.4
PHP: 5.6.19 (apache2handler)
OS: Linux 4.1.13-19.31.amzn1.x86_64 x86_64
MySQL: 5.5.46
Apache: 2.4.18

**Comment by adehner** [comment]
Hi Anurag,

I agree that this is an awesome plugin! But 1+ on the collections issue. I would love to use it on a site I'm building.

Anneliese

**Comment by anuragji** [comment]
I finally have my dev server up and running again. A preliminary test on my local machine appeared to be working correctly, but that is using Omeka 2.3.1. I'll upgrade to 2.4 and check again. @adehner can you confirm the Omeka version you are running?

**Comment by anuragji** [comment]
I can't seem to be able to reproduce the issue. For both Omeka 2.3 and 2.4 the Default sort for collections appears to be working correctly. I am not sure if you can run it through a debugger to see exactly what is going on. The section to look at would be `filterCollectionsBrowseParams($params)` in _DefaultSortPlugin.php_. The sort parameters configured in the plugin backend are pulled from the DB and applied to `$params`. Sorry to not be able to be of more help.

**Comment by adehner** [comment]
Thanks Anurag.

I'm using Omeka 2.4 and trying to sort by Dublin Core Identifier, but the
collections continue to sort by date added. I am also using the Collection
Tree plugin. However, I tested the sorting with Collection Tree
deactivated, and the issue persisted.

I'll try running it through a debugger and see if I can get to the bottom
of it.
