### ISSUE TITLE
There seems to be an an issue with Collections sorting

### ISSUE THREAD

**Issue by DBinaghi** [anuragji/DefaultSort#7]
Hi.
Your plugin works perfectly with Items, but I seem to have a problem with Collections: no matter what I do, it's just ignoring the new sort field and direction set in the config form.
I've just found out, that, if I add another filter (`filterCollectionsBrowseDefaultSort`), leaving it empty, then the values set in the config form are used, and the plugin works like it should.
Is there any reason why this happen? Have you experienced anything similar?
Thanks

**Comment by anuragji** [comment]
@DBinaghi unfortunately no. I also haven't worked with Omeka for a while, and no longer have access to a Dev environment. I would recommend stepping through it with a debugger in order to monitor the vars during code execution.

Sorry for not being able to be of more assistance. I am more than happy to implement a pull request. 

Bon chance!

**Comment by DBinaghi** [comment]
Thanks for your quick reply.

I've found out what has happened, in the meantime: in 2017 they've deleted the browseAction from the CollectionsController, thus creating the problem with the filter.

I'm not sure why calling the newest filter triggers the old, though. But I'm trying to pass the code to the new filter, if I'll succeed I will turn into a pull request.

Best regards

**Comment by anuragji** [comment]
That makes sense - thank you!

**Comment by DBinaghi** [comment]
Done. Sent 4 pull requests.

Thanks again for your plugin.

**Comment by anuragji** [comment]
@DBinaghi - thank you.

Quick question - you did mention that the browseAction was depreciated in 2017. Do you happen to know what Omeka Version that corresponds to? We should update the documentation to indicate that the updated version is compatible with Omeka x.x.x.+

Relatedly, I assume (and again, I do not have a dev environment) that this means that versions prior to 2017 will now no longer be supported by this current code base. Is that correct?

**Comment by DBinaghi** [comment]
I am not sure why they decided to delete that function from CollectionsController, I saw this (https://forum.omeka.org/t/changing-collections-default-sort-not-working/4929) and then this (https://github.com/omeka/Omeka/commit/d7dccce912b6c7e1ac307424388f1431ea5d7a50), Nov 2017.

After that date, I would say it was impossible for the Collections part of your plugin to work. Items was still working, as I previously said.

I suppose you could add also the previous filters, as a redundant backup; but maybe the filter I'm using now has always been there... hard to tell.

Hope this helps.

**Comment by DBinaghi** [comment]
Hi. I think I've found the bug, so reverted to previous filters (thus no problem with compatibility) while fixing them. See pull requests. Hope this helps.

**Comment by DavidGhedini** [comment]
Hi -
I'm experiencing this issue as well.
Do you plan on merging the pull request from @DBinaghi ?
Thanks

**Comment by DBinaghi** [comment]
> Hi -
> I'm experiencing this issue as well.
> Do you plan on merging the pull request from @DBinaghi ?
> Thanks

David, see whether my fork https://github.com/DBinaghi/DefaultSort helps you and let me know.

**Comment by DavidGhedini** [comment]
Hi @DBinaghi
I used Patch 4 and it fixed the issue for me.
Thanks!
David

**Comment by librarygnome** [comment]
Same problem, plugin doesn't work in Collection show. Patch #4 isn't working for me, but I have no idea why. I suspect it has to do with the Foundation alpha theme?
